### ISSUE TITLE
부모 헤더가 각각 하나씩 구분되어 있습니다.

### ISSUE THREAD

**Issue by krdn** [ibsheet/loader-vue-guide-samples#1]
![image](https://user-images.githubusercontent.com/5511718/171857254-3f6be55c-5130-492b-a940-3a7f70fa57c6.png)

위의 헤더가 아래와 같이 부모 헤더가 하나로 통합되어야 하는데 각각 나누어져 있음

![image](https://user-images.githubusercontent.com/5511718/171857340-3ac0a007-1622-4832-b30f-67e96ab3f775.png)

**Comment by hojae-lee** [comment]
@krdn 처음 시트는 머지가 되지 않은 시트로 시트 위의  `select` 를 변경시에 자동으로 머지되게끔 기능을 구현하였습니다. <br/>
![image](https://user-images.githubusercontent.com/55069045/172772042-129e43ae-0d5b-42f8-a562-25f36902bfa7.png)

문의: @milo37

**Comment by krdn** [comment]
감사합니다.
