### ISSUE TITLE
컬럼 별 타입 에 문의드립니다.

### ISSUE THREAD

**Issue by KangJoonGu1** [ibsheet/loader-vue-guide-samples#4]
제가 작업중인게 조회버튼을 클릭하여 컬럼 별 타입 과 같은 리스트가 보여지는데, 리스트 내에 콤보와 날짜가 들어있습니다.

해당 항목들을 선택이 안되게 처리해야하는데 어떻게 하는지요?

리스트 통째로 저장을 넘겨야해서 각 value 값들은 그대로 있어야하고, 선택만 안되게 처리해야하는데 예시가 없어서 문의드립니다.

**Comment by hojae-lee** [comment]
안녕하세요.   <br/>
`CanSelect` 속성을 이용하여 처리할 수 있습니다. 아래와 같이 CanSelect: 0 으로 입력하시면 선택이 되지 않도록 처리할 수 있으니 참고해주시기 바랍니다.

아래의 **api 문서**를 링크로 달아놓겠습니다. <br/>
https://docs.ibleaders.com/ibsheet/v8/manual/#docs/props/col/can-select

```js
  "Cols": [
      {
        Header: '콤보(Enum)',
        Type: 'Enum',
        Name: 'ComboData',
        Width: 100,
        Align: 'Right',
        Enum: '|대기|진행중|완료',
        EnumKeys: '|01|02|03',
        CanSelect: 0 // 선택 불가
      },
]
```

**Comment by KangJoonGu1** [comment]
답을 주셔서 감사드립니다.

한가지 더 문의할게 있습니다.

모든 컬럼에서는 알려주신데로 처리가 되는데요,

조회 후 나온 리스트에서는 선택이 되지않고,

새로운 행을 추가하여 해당 행에만 바로 입력을 받게 하는 형식이어서 해당 부분만 콤보가 다시 선택이 되게 살리고 싶습니다.

방법을 부탁드립니다.

**Comment by hojae-lee** [comment]
입력을 받게하는 부분으로 CanFocus 를 이용한 방법에 대해서는 아래와 같이 사용할 수 있습니다. 참고용입니다.
addRow시 init 속성을 이용하여 속성을 넣는 방법을 사용한 가이드 입니다.

https://jsfiddle.net/37cg04sk/2/

CanSelect 를 이용해서는 위와 같은 형식을 만들지 못하는 문제가 있어 좀 더 생각해보겠습니다.

**Comment by KangJoonGu1** [comment]
빠른 답변 감사드립니다!

아무래도 제가 작업중인곳에 개발되어진걸로는 알려주신 방법이 잘 먹지를 않네요..

혹시 조회 후 나온 그리드에서 몇번째행에 몇번째열만 특정 부분만 지정을 해서 .CanEdit = 0; 를 하려고 합니다.

CanEdit = 0; 이거는 잘먹는거 같아서 이거를 쓰려하는데, 특정 부분 지정을 못하겠습니다.

this.$refs.grid1.sheet.Cols["AAA"].CanEdit = 0;
이렇게 하면 AAA 컬럼 전체가 다 해당이되버리니 잘 안되네요.

**Comment by hojae-lee** [comment]
행을 추가시에 추가된 셀에 `CanEdit` 을 1로 변경하는 방법이 있습니다.
그러면 기존 컬럼에 CanEdit 상태는 0 이지만, 추가된 셀에 상태가 CanEdit:1 이기 때문에 사용가능합니다.

```js
sheet.addRow({ init: { AAACanEdit: 1 } })
```

다른 방법으로는 attribute + formula 를 사용하는 방법이 있습니다. 아래와 같이 Def.Row 에 CanFormula 와 CalcOrder 를 적으시고  컬럼에 CanEditFormula 를 걸어 사용하는 방법입니다.

```js
  "Def": {
    "Row": {
      "CanFormula": 1,
      "CalcOrder": "ComboDataCanEdit"
    }
  },
 ... 

 "Cols": [
    {"Header": "문자열(Text)","Type": "Text","Name": "TextData","Width": 100,"Align": "Center","CanEdit": 1},
    {"Header": "콤보(Enum)","Type": "Enum","Name": "ComboData","Width": 100,"Align": "Right","Enum": "|대기|진행중|완료","EnumKeys": "|01|02|03", CanEditFormula: caneditfunc}
],
....

// 만약 행의 상태가 Added 면 CanEdit 을 1, 아닌 경우에는 CanEdit: 0 으로 해줌.
function caneditfunc (fr) {
	if (fr.Row.Added) return 1;
  return 0;
}
```

포뮬러관련 예제

https://jsfiddle.net/kncmf7ug/

위의 API 동작으로 간단하게 처리된다면 전자의 방법을 추천 드립니다.

**Comment by KangJoonGu1** [comment]
잘 알려주신 덕분에 문제를 모두 해결했습니다.

너무 너무 감사드립니다!!!

좋은 하루 보내세요!!
