### ISSUE TITLE
Grid 합계행 Select 하여 복사하고자 합니다. 

### ISSUE THREAD

**Issue by krdn** [ibsheet/loader-vue-guide-samples#5]
![image](https://user-images.githubusercontent.com/5511718/182315443-a753cd2e-b5aa-40f9-8adc-2448428a59de.png)

https://jsfiddle.net/api/post/library/pure/

어떤 설정을 변경하여야 할까요

**Comment by milo37** [comment]
@krdn  안녕하세요. 
제품 사용 관련 문의는 https://portal.ibsheet.com/support/home 로 남겨주시면 빠른 답변을 받을 수 있습니다.
감사합니다.
